lightway-server/src/connection.rs, lightway-server/src/connection_manager.rs, lightway-server/src/io/outside/tcp.rs
In TCP server, we create a tokio task for each TCP connection (unlike UDP, where there
is only one tokio task) and it waits on TCP socket to recv packets.
During normal client disconnects, tcp socket read will return 0/Err and the task exits.
But in case of network failure, it is possible tcp socket stays alive, until TCP keepalive
times out.
Instead of waiting for TCP keepalive, close the socket proactively in case the connection
is not online
Inactive lightway connections are aged out and closed regularly and this proactive TCP close
will be useful in those evictions.
Close TCP on disconnect and save resource
Verified the TCP state is cleared from kernel after the timeout.
=> Server: Close tcp connections on expiry/aged out

lightway-client/src/io/outside/udp.rs, lightway-client/src/lib.rs, lightway-client/src/main.rs, lightway-server/src/io/outside/udp.rs
With single threaded tokio runtime, the udp sockets return WouldBlock,
until we explicitly request the socket to be writable (UdpSocket::writable()).
The behavior seems different in multi threaded runtime, where it gets enabled
after the first few calls.
Since the outside io send is called from WolfSsl's callback which is not async,
we do not have a way to enable UdpSocket to be writable()
This causes the UDP lightway connection to fail, in case of single threaded environment.
i.e WolfSsl is not able to handle send failures, during initial negotiation
This commit makes the socket to be writable as soon as it is created, so that
WolfSsl can use sync send directly successfully.
We saw inconsistent crashes in our CI with WolfSsl error …
=> Fix UDP lightway connections failure in single threaded runtime

lightway-app-utils/src/sockopt.rs, lightway-app-utils/src/sockopt/ip_mtu_discover.rs, lightway-app-utils/src/sockopt/ip_pktinfo.rs
Since iOS also doesn't support SOL_IP, we are now updating the some of the libc constant to be built conditionally based on `target_vendor = "apple"` instead of just MacOS.
We have also updated `socket_enable_pktinfo` to be built/included only when we are not using an apple platform.
Originally, `socket_enable_pktinfo` can't be built on Mac/iOS platform because mac/ios platform doesn't have `SOL_IP` in libc. So this PR fixes this, and allows us to build libraries on apple platforms.
Tested our internal clients can be built on iOS platform (`aarch64-apple-ios`, `aarch64-apple-ios-sim`) when it's referencing this new branch and includes `lightway-core`, `lightway-client`, `lightway-app-utils` in their dependency
=> app-utils: conditionally build libc constants for Apple instead

lightway-app-utils/src/connection_ticker.rs, lightway-client/src/lib.rs, lightway-core/src/connection.rs, lightway-core/tests/connection.rs, lightway-server/src/connection.rs
Spawn the ticker task in JoinSet only if it is going to be stored. Else create as normal tokio task
which will be killed when Channel sender is dropped
Found ticker is not working in server while testing.
Manually verified the tick is properly called after timer expiry
```
2025-03-21T03:02:26.241855Z  INFO lightway_core::connection: Update TLS keys session=c8fece5b7d4d8de7
2025-03-21T03:02:26.242026Z DEBUG lightway_core::connection: event event=TlsKeysUpdateStart
2025-03-21T03:02:26.242076Z TRACE lightway_core::connection: Scheduling tick for 100ms
2025-03-21T03:02:26.242151Z TRACE handle_events:handle_tls_keys_update_start: lightway_server::metrics: Begin session rot
ation
2025-03-21T03:02:26.243634Z DEBUG lightway_core::connection: event event=TlsKeysUpdateCompleted …
```
=> Disconnect connection when session rekey failed

Cargo.lock, Cargo.toml, deny.toml, lightway-app-utils/Cargo.toml
This PR fixes building/compilation issue when we are building it in tvOS.
We are manually setting these crates to use a specific commits/PRs as we are waiting for a new official release from them:
1. fs-mistrust:
Gitlab can only make reference to commits on the main branch only, so we are using the commit hash for the merge request on main
https://gitlab.torproject.org/tpo/core/arti/-/commit/0f13b7a0e19b3fae163e76c8ade6499244abf834
2. ctrlc
https://github.com/Detegr/rust-ctrlc/pull/128 to support building or compiling on tvOS.
Bumped `wolfssl` and `tun` to a new version that supports building on tvOS as well.
Support tvOS
By building the internal client on all 3 tvOS platforms
=> CVPN-1893 Support building on tvOS

lightway-core/src/connection.rs, lightway-server/src/connection.rs, lightway-server/src/connection_manager.rs, lightway-server/src/io/outside/tcp.rs, lightway-server/src/lib.rs, lightway-server/src/metrics.rs
Disconnect the lightway clients properly if session rekeying failed.
On previous commit, we fixed the timers which is needed to kickout the client
https://github.com/expressvpn/lightway/pull/174/commits/7f9f08d3142a50cdfdc74fcf4ab8ba843df0c2cb
But the disconnect was not proper and we just set the state to Disconnected. This causes the assigned IP address to leak.
Fix it properly by disconnecting client using Connection::disconnect()
Fixed metrics which were off since this commit https://github.com/expressvpn/lightway/pull/174/commits/d09b07d65e2a8feb6727675f7605831924027545
The above commit introduces a new fatal error `Disconnected` on Connection::inside_data_received and Connection::outside_data_received apis.
And since this is a fatal error, it also call …
=> CVPN-1878: Disconnect properly when dtls rekey fails

Cargo.lock, deny.toml, lightway-app-utils/Cargo.toml
There's a new release of v0.9.1 for fs-mistrust that now support tvOS, so we revert to use the official release from crates-io 
Use official release instead of commit hash
Passed internal CI on tvOS
=> app-utils: use official v0.9.1 fs-mistrust for tvOS

lightway-server/src/connection.rs, lightway-server/src/io/outside/tcp.rs
Disconnect lightway in case of TCP shutdown or other fatal failures.
Note that it is possible, disconnect has been called in `conn.handle_outside_data_error` already in case of fatal error case. It is still fine to call it again, since `disconnect` call is idempotent and no-op if it is already disconnected
But we need this disconnect in case of TCP connection shutdown. Otherwise Server::Connection will be leaking.
TCP connections are not getting closed in some servers
Verified in running prod server
=> server: disconnect lightway in case of TCP shutdown or other fatal failures

lightway-core/src/connection.rs, lightway-server/src/connection.rs, lightway-server/src/connection_manager.rs
When we initiate a session id rotation, we store the new session id along with
strong pointer of lightway_server::Connection inside the HashMap. We remove this
HashMap entry, when session rotation is completed.
In case the session rotation does not succeed, HashMap entry is not cleared
i.e. the strong pointer to Connection inside entry, is also not released and thus Connection gets leaked.
There are two issues in the current approach:
1. Using strong pointer to Connection inside pending_session_id_rotations HashMap
2. Not cleaning up the pending_session_id_rotations HashMap periodically
First problem is fixed by using Weak pointer to Connection inpending_session_id_rotations.
And the second issue by creating a task which periodically checks for connection and clean-up if connection is …
=> server: cleanup pending_session_id_rotations for disconnected clients

Cargo.lock, Cargo.toml, deny.toml
Use the official release from ctrlc that brings support to tvOS, so that we don't need to rely on the branched PR: https://github.com/Detegr/rust-ctrlc/releases/tag/3.4.6
Use the new official release instead
N/A
=> workspace: use ctrlc 3.4.6 release for tvOS support

lightway-server/src/connection_manager.rs
Commit https://github.com/expressvpn/lightway/commit/bccfc81fbd2bc4ceaa57795b6bdc1a65ae581627 fixes the leaking UDP sessions. But it introduces a deadlock, by trying to lock the same Mutex twice consecutively on error condition.
Luckily our parking lot deadlock detection pin pointed it out.
Fixing it by locking once and using the same guard for removing stale entry.
Server instances are restarted frequently
Verified in prod that instances are stable without deadlock
=> server: fix deadlock of pending_session_id_rotations mutex

lightway-server/src/connection.rs
There is a potential deadlock with server::Connection mutex and pending_session_ids mutex.
Consider the following flow:
1. Client moves from Wifi to Celuular and the IP changes, and lightway is trying t float the UDP connection
2. Connection::begin_session_id_rotation will lock the connection mutex and update lightway_core to rotate session id and then add the server::Connection to pending_session_id_rotations after locking it.
3. At the same time, traffic from client started using new pending_id. This will be processed in server::outside_io::udp::run() -> data_received()
4. In data_received() api, we will try to find the connection belonging to that new pending_session_id using find_or_create_datagram_connection_with() call.
5. In this api, we lock the pending_session_id_rotations mutex …
=> server: drop connection mutex to avoid deadlock

.github/workflows/ci.yaml, Earthfile, README.md, lightway-app-utils/src/sockopt/ip_pktinfo.rs, lightway-app-utils/src/tun.rs, lightway-client/Cargo.toml, lightway-client/src/args.rs, lightway-client/src/main.rs
One missing piece to enable compiling lightway client on macOS.
Lightway server needs some more cleanup, so not enable in this PR.
Client may still need lack some features since it is not tested fully. But this PR prevents the future compilation break on macOS.
After we test mac client thoroughly, we can add tests for macOS CI builds too.
Added CI to build lightway-client on macos to prevent compilation break
Verified lightway-client is working in M1 macbook
=> Support building lightway client on macOs

docs/logs_and_metrics.md, lightway-app-utils/src/lib.rs, lightway-app-utils/src/packet_codec.rs, lightway-client/src/args.rs, lightway-client/src/lib.rs, lightway-core/src/connection.rs, lightway-core/src/connection/builders.rs, lightway-core/src/context.rs, lightway-core/src/lib.rs, lightway-core/src/metrics.rs, lightway-core/src/packet_codec.rs, lightway-server/src/args.rs, lightway-server/src/codec_list.rs, lightway-server/src/connection.rs, lightway-server/src/connection_manager.rs, lightway-server/src/lib.rs, lightway-server/src/main.rs
- Added an encoded/decoded packet mpsc channel interface to PacketCodec.
- Whenever a packet is ready to be emitted by the encoder/decoder, it is sent to the mpsc channel, and the client/server is responsible for sending the packets to the core.
- packets are no longer sent as a batch, and is sent one by one when received from the mpsc channel.
- Removed the periodic flush logic of the encoder
For now:
- Flushing of encoded packets can only be triggered by the periodic flush task and the receive of inside data 
- Flushing of decoded packets can only be triggered by the receive of outside data
which is not ideal because the codec cannot actively trigger a send to the core when the packets are ready, and can only passively wait for a flush.
If the packets sit in the codec for too long, the …
=> CVPN-1958 Allow inside codec to actively flush the encoded/decoded pkts

.github/workflows/weekly-cargo-update.yaml, deny.toml
Upstream dogstatsd exporter has been moved to metrics org recently and with the move, code has been refactored with some features dropped like consolidating metrics in single UDP packet etc.
Ref: 
https://github.com/metrics-rs/metrics/issues/554
https://github.com/metrics-rs/metrics/issues/560
Until it is fixed, ignore the outdated error for metrics-util crate.
Weekly cargo update is continuously failing with cargo outdated check.
https://github.com/expressvpn/lightway/actions/workflows/weekly-cargo-update.yaml
This error will prevent us to check other outdated packages.
Temporarily ignore metrics-util until the above issue is fixed.
And another cargo deny error:
https://github.com/expressvpn/lightway/actions/runs/14987755691/job/42104785560
=> ci: temp ignore metrics-util crate for outdated check

lightway-app-utils/Cargo.toml, lightway-app-utils/src/lib.rs, lightway-app-utils/src/wolfssl_tracing.rs, lightway-client/Cargo.toml, lightway-client/src/lib.rs, lightway-server/Cargo.toml, lightway-server/src/main.rs
Call `set_logging_callback` for debugging WolfSSL when `debug` feature is on. This makes debugging WolfSSL easier as we don't have build WolfSSL from scratch everytime we want debug logs from it.
Easier to read and get debug logs from WolfSSL without jumping a bunch of hoops
Able to obtain WolfSSL logs on Android using the same callback function
=> Call set_logging_callback for debugging WolfSSL

docs/inside_packet_codec.md, lightway-app-utils/src/codec_ticker.rs, lightway-app-utils/src/lib.rs, lightway-client/src/lib.rs, lightway-core/src/connection.rs, lightway-core/src/connection/builders.rs, lightway-core/src/context.rs, lightway-core/src/encoding_request_states.rs, lightway-core/src/lib.rs, lightway-core/src/wire.rs, lightway-core/src/wire/encoding_request.rs, lightway-core/src/wire/encoding_response.rs
- Request id and response id in `EncodingRequest` and `EncodingResponse` wire frame types. 
- Each unique request id corresponds to exactly 1 unique request
- Use case: chronological order of each unique request
- We may safely assume the id does not overflow, as it takes > 500 years to overflow it even one encoding request is made per nanosecond. 
- Re-transmission of `EncodingRequest` inside wire frame
- A ticker is created in `lightway-client` to schedule for the next re-transmission (Similar to the pattern of `ConnectionTicker`.
- Each schedule corresponds to a request by its id. Hence, stale request ticks are disabled accordingly.
- The number of re-transmission is limited by a constant to avoid wasting network resources in case the server does not have encoding enabled.
- Handling …
=> CVPN-1824 Encoding Request Retransmission

lightway-client/src/args.rs, lightway-client/src/lib.rs, lightway-client/src/main.rs, lightway-core/src/connection.rs, lightway-core/src/connection/builders.rs, lightway-core/src/connection/dplpmtud.rs, lightway-server/src/connection_manager.rs, lightway-server/src/io/outside/udp.rs
Make the base_mtu of PMTUD as config value
At present, PMTUD uses default value of 1250 as base MTU.
By making the base_mtu as configurable, we can allow PMTU discovery  to be usable
even in networks which has lesser MTU than 1250
Verified PMTUD starts from the configurable value
=> Make pmtu base config

lightway-core/tests/connection.rs, lightway-core/tests/packet_codec.rs
Adding inside packet codec to `lightway-core`'s `Connection`'s  automated tests.
The automated tests cases gives a better code coverage to the inside packet codec functionalities, making it easier to re-factor the related functionalities in the future.
Some manual sanity checks are done to make sure that the tests are meaningful:
- Forcing packet codec to be used in Lightway TCP tests => test cases fail
- Sabotaging the `TestPacketEncoder` and `TestPacketDecoder` by making them spitting incorrect packets => test cases fail
=> CVPN-1988 Packet Codec test cases in Connection

lightway-client/src/io/outside/udp.rs
Until now, we were hardcoding UDP client socket to bind to Ipv4 address, before connecting to server.
This prevents the client from connecting to Ipv6 server.
With this change, client UDP sockets will be bound to v4/v6 protocol, based on server ip address.
Note that this is not needed for TCP since we connect to server address directly which will take care of creating the socket with correct protocol. For UDP, there is no such api which can connect directly. Only way is to bind to local socket and then use it.
Found Ipv6 UDP traffic is not working with Ipv6 servers.
Manually verified lightway client and server can communicate using Ipv6 protocol using Ipv4 in tunnel.
=> Client: Bind to v4 or v6 based on server Ip protocol

lightway-core/src/connection.rs
Introduce `set_new_outside_io` to update outside IO callback in WolfSSL session.
This can be used when the client apps need to destroy/recreate the outside socket to make sure the same WolfSSL session can still be used for this connection.
Tested this on a test iPhone, verified that the WolfSSL session is using the new callback arguments properly.
=> CVPN-1935: Add `set_outside_io` to update outside IO callback

.cargo/config.toml, .github/workflows/ci.yaml, Earthfile
Introduce tests via running qemu and CI jobs for compiling to the `riscv64gc` target.
This is to ensure `riscv64gc` targets are covered under the tests
=> ci: add tests for riscv64gc

lightway-core/src/connection.rs, lightway-core/src/context/server_auth.rs, lightway-core/src/features.rs, lightway-core/src/lib.rs, lightway-core/src/metrics.rs, lightway-core/tests/connection.rs, lightway-server/src/auth.rs
By default, in `lightway-server`, inside packet encoding is enabled. The application can choose to override this behaviour in its `ServerAuth` implementation.
A new `features()` function is added to `ServerAuthHandle`. This allows the Server to specify which features are available to the connection during authorization. An application can choose to override this field in its `ServerAuth` implementation.
This will allow applications to control which connections can use inside packet encoding.
Unit tests are added to check if `can_use_inside_pkt_encoding` defaults to true. This maintains existing behaviour, so is not breaking.
=> feat: let ServerAuth determine if inside packet encoding can be used

lightway-core/tests/connection.rs
Increase test timeout from 2000ms to 5000ms.
This change is needed to solve flaky tests, especially the RISC-V tests, where emulation incurs a significant performance overhead.
=> Increase tests timeout for riscv CI

.github/workflows/ci.yaml, README.md
remove earthly satellite in github actions since satellites will be sundown by July 16, 2025.
Read more:
https://earthly.dev/blog/shutting-down-earthfiles-cloud/
Earthly satellites are shutdown
CI passed
=> ci: remove earthly satellite in github actions

Cargo.lock, flake.nix, lightway-core/Cargo.toml
This change is introducing an option to use the system’s CA trust store for TLS certificate verification. This enhancement is designed to give downstream developers greater flexibility, such as making HTTPs API calls that use a Root CA-signed certificate. Please note, however, that this change does not mean that Lightway will begin accepting Root CA-signed certificates.
This change only adds the capability to WolfSSL. To use this feature, developers will need to call a specific function to load the system's certificates into the WolfSSL context. This process does not affect existing certificate validation unless explicitly enabled by the developer.
Mirroring the change from https://github.com/expressvpn/lightway-core/pull/200
Manually tested.
=> CVPN-2123 Enable System CA Certs feature in WolfSSL

Earthfile, lightway-client/src/routing_table.rs
Ignores routing table test by default.
This allows developers to test without being impaired by their local network conditions.
We still keep the CI tests to ensure it works.
=> Ergonomic route table tests

lightway-client/src/main.rs, tests/Earthfile, tests/client/client_config.yaml, tests/client/docker-entrypoint.sh, tests/e2e/docker-compose.yml
Previously parsing a hostname to the config would throw an error
This fixes it so that the hostname is resolved in the binary
`config.server` is now resolved in `to_socket_addrs()`
scripts that use dig to resolve have been modified to rely on the binary
=> client: Fix user unable to state server hostname

Cargo.toml, lightway-client/Cargo.toml
This should prevent platforms that are not
supported by route_manager from trying to resolve
this dependency even when it is unused
=> client: Added conditional dependencies

.github/workflows/weekly-cargo-update.yaml
use | instead of / in sed expression 
Sha256 value of cargo is base64 encoded string. So it can have / and + in addition to alphanumeric characters.
This messes up the sed expression when the expected output have `/`
Fix it by using `|`
CI failed when updating wolfssl
https://github.com/expressvpn/lightway/actions/runs/16587896125/job/46916736346
Verified sed expression succeeded with / in expected output
=> ci: use | instead of / in sed expression

lightway-core/src/utils.rs, lightway-server/src/args.rs, lightway-server/src/ip_manager.rs, lightway-server/src/ip_manager/ip_pool.rs, lightway-server/src/lib.rs, lightway-server/src/main.rs
Add cli option to disable ip pool randomization
This configuration is not available as default, and should not be used in production.
It can be used for debugging purposes only.
Make testing or debugging easier, by disable Ip pool randomization.
Verified the config is enabled only when `debug` feature is enabled.
Added unit tests to test Ip pool with and without randomization
=> Server: Add debug option for disabling Ippool randomize 

Earthfile, lightway-app-utils/src/args/cipher.rs, lightway-app-utils/src/args/connection_type.rs, lightway-app-utils/src/tun.rs, lightway-client/Cargo.toml, lightway-client/src/args.rs, lightway-client/src/debug.rs, lightway-client/src/io/inside.rs, lightway-client/src/io/inside/tun.rs, lightway-client/src/lib.rs, lightway-client/src/main.rs, lightway-server/src/io/inside/tun.rs, lightway-server/src/lib.rs, tests/Earthfile, tests/client/Earthfile, tests/client/check-server.sh, tests/client/docker-entrypoint.sh, tests/client/parallel_connect/client_config.tcp.yaml, tests/client/parallel_connect/client_config.tcp_then_udp.yaml, tests/client/parallel_connect/client_config.udp.yaml, tests/client/parallel_connect/client_config.udp_then_tcp.yaml, tests/e2e/Earthfile, tests/e2e/docker-compose.parallel_connect.yml, tests/e2e/run-parallel-connect-test.sh, tests/e2e/run-with-compose-stack.sh
Adds support for multiple server connections in lightway-client. The servers are connected in parallel and after the "best connection" is chosen, all other connections are disconnected.
The configuration file now supports specifying multiple servers via the `servers` field, and falls back to the single-server configuration if `servers` is not specified. This maintains full backward compatibility with existing server configurations.
The client attempts to connect to all servers at once. After the first connection is established, if `defer_connect_timeout` is set, we wait that duration before choosing the best connection. The best connection is the first connection in the order of the original list of servers that manages to connect within the specified `defer_connect_timeout`.
Improves …
=> client: Parallel connect

flake.lock
Update nix flake to include latest rust version.
Ideally this has to be done with nightly ci check. But usually there will be a gap where the new version is released and is updated in rust-overlay flake. So keeping it manual for now.
Keep nix in sync with other build systems.
Verified the rust version is 1.89.0 after upgrading
CI run should pass
=> nix: flake update to move rustc version to 1.89.0

lightway-client/src/args.rs, lightway-client/src/dns_manager.rs, lightway-client/src/lib.rs, lightway-client/src/main.rs, lightway-client/src/routing_table.rs, tests/client/client_config.yaml, tests/client/parallel_connect/client_config.tcp.yaml, tests/client/parallel_connect/client_config.tcp_then_udp.yaml, tests/client/parallel_connect/client_config.udp.yaml, tests/client/parallel_connect/client_config.udp_then_tcp.yaml
This PR aims to provide users the option to setup the DNS configuration.
We provide a `dns_config_mode` flag which users can set to `Default` or `NoExec` 
Grants users more power to customize runtime behaviour. On some platforms, not all runs will require DNS configuration.
unittests
Running the VPN in both modes
=> client: Added flag for dns_config options

lightway-client/src/lib.rs
During an intended disconnect, ensure we wait for the Disconnect state before we abort tasks. This allows the graceful disconnect to take place.
The existing implementation does not wait for the Lightway connection to fully disconnect before aborting tasks. This causes the connection to not go through the usual disconnect state changes.
This is fixed by waiting for the `Disconnect` state if the client requests a disconnect before the client can exit.
Manually test and check that all state transitions are correctly logged.
=> client: graceful disconnect

lightway-app-utils/src/connection_ticker.rs
use warn instead of error on DTLS timeout
Having error message server will trigger sentry alert. Since this is not critical, use warn instead of error
To avoid unnecessary alerts on server.
Verified warning has been raised instead of error log.
=> app-utils: use warn instead of error on DTLS timeout

lightway-app-utils/src/event_stream.rs, lightway-client/src/lib.rs, lightway-client/src/main.rs, lightway-core/src/connection.rs
In all the contexts where it is used, `EventCallback` is already mutable. We expose this mutability to it so it can maintain its own state.
This allows an `EventCallback` implementation to be stateful without interior mutability.
Tests should pass
=> core: Allow EventCallback to be mutable

Cargo.lock, Cargo.toml, deny.toml, flake.nix, lightway-app-utils/Cargo.toml, lightway-app-utils/examples/udprelay.rs, lightway-app-utils/src/tun.rs, lightway-client/Cargo.toml, lightway-client/src/io/inside/tun.rs, lightway-client/src/lib.rs, lightway-client/src/main.rs, lightway-client/src/routing_table.rs, lightway-core/src/io.rs, lightway-core/tests/connection.rs, lightway-server/src/io/inside/tun.rs, lightway-server/src/main.rs
This PR moves away from using rust-tun and replaces it with tun-rs
`config.enable_routing(false)` was previously used as otherwise the tun crate would add this route on macos
```
Destination        Gateway            Flags               Netif Expire
100.64/24          100.64.0.5         UGSc             utun1995       
```
the tun-rs crate does not exhibit this behaviour and so such an option is not implemented by `TunConfig`. However,
tun-rs crate does seem to add this route on macos
```
Destination        Gateway            Flags               Netif Expire
100.64.0.6         link#23            UHS              utun1995       
```
which is not a problem as long as we set `device.associate_route(false)` on macos
Among other reasons, tun-rs exposes methods with `&self` rather than `&mut …
=> CVPN-2114: Migration tun to tun-rs
